[package]
name = "gloo-timers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gloo-timers = "=0.2.3"
# gloo-timers = "=0.2.2"
wasm-bindgen = "0.2.79"
